<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Membership\Test\MembershipBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
    'Membership\Module'                                        => __DIR__ . '/Module.php',
    'Membership\Model\MembershipBase'                          => __DIR__ . '/src/Membership/Model/MembershipBase.php',
    'Membership\Model\MembershipWidget'                        => __DIR__ . '/src/Membership/Model/MembershipWidget.php',
    'Membership\Model\MembershipAdministration'                => __DIR__ . '/src/Membership/Model/MembershipAdministration.php',
    'Membership\Model\MembershipConsole'                       => __DIR__ . '/src/Membership/Model/MembershipConsole.php',
    'Membership\View\Widget\MembershipUserLevelsWidget'        => __DIR__ . '/src/Membership/View/Widget/MembershipUserLevelsWidget.php',
    'Membership\View\Widget\MembershipAbstractWidget'          => __DIR__ . '/src/Membership/View/Widget/MembershipAbstractWidget.php',
    'Membership\View\Widget\MembershipLevelWidget'             => __DIR__ . '/src/Membership/View/Widget/MembershipLevelWidget.php',
    'Membership\View\Helper\MembershipImageUrl'                => __DIR__ . '/src/Membership/View/Helper/MembershipImageUrl.php',
    'Membership\Event\MembershipEvent'                         => __DIR__ . '/src/Membership/Event/MembershipEvent.php',
    'Membership\Controller\MembershipConsoleController'        => __DIR__ . '/src/Membership/Controller/MembershipConsoleController.php',
    'Membership\Controller\MembershipAjaxController'           => __DIR__ . '/src/Membership/Controller/MembershipAjaxController.php',
    'Membership\Controller\MembershipAdministrationController' => __DIR__ . '/src/Membership/Controller/MembershipAdministrationController.php',
    'Membership\PaymentHandler\MembershipHandler'              => __DIR__ . '/src/Membership/PaymentHandler/MembershipHandler.php',
    'Membership\PagePrivacy\MembershipBuyPrivacy'              => __DIR__ . '/src/Membership/PagePrivacy/MembershipBuyPrivacy.php',
    'Membership\Exception\MembershipException'                 => __DIR__ . '/src/Membership/Exception/MembershipException.php',
    'Membership\Form\MembershipAclRole'                        => __DIR__ . '/src/Membership/Form/MembershipAclRole.php',
    'Membership\Form\MembershipFilter'                         => __DIR__ . '/src/Membership/Form/MembershipFilter.php',
];
