<?php $this->declareVars('subPageTitle', 'parentPageTitle') ?>

<?php $this->subPageTitle = $this->translate('Add a role') ?>
<?php $this->parentPageTitle = $this->translate('List of membership levels') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('membership/membership-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'membership-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'add_role' => [
            'name' => $this->subPageTitle,
            'controller' => 'membership-administration',
            'action' => 'add-role',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('New membership'),
    'body' => $this->partial('partial/form', ['form' => $this->role_form])
]) ?>