<?php $this->declareVars('subPageTitle') ?>

<?php $this->subPageTitle = $this->translate('Edit the role') ?>
<?php $this->parentPageTitle = $this->translate('List of membership levels') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('membership/membership-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'memberships-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'edit_role' => [
            'name' => $this->subPageTitle,
            'controller' => 'memberships-administration',
            'action' => 'edit-role',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'memberships-administration',
        'action' => 'delete-roles',
        'name' => $this->translate('Delete the role'),
        'check_acl' => true,
        'confirm' => $this->translate('Role will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'roles' : [{$this->role['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'memberships-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'memberships-administration',
        'action' => 'add-role',
        'name' => $this->translate('Add a role'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Editing'),
                'body' => $this->partial('partial/form', [
                    'form' => $this->role_form,
                    'controller' => 'memberships-administration',
                    'action' => 'edit-role',
                    'params' => [
                        'slug' => $this->role['id']
                    ]
                ])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Editing'),
                'body' => $this->partial('partial/form', [
                    'form' => $this->role_form,
                    'controller' => 'memberships-administration',
                    'action' => 'edit-role',
                    'params' => [
                        'slug' => $this->role['id']
                    ]
                ])
            ]) ?>
        </div>
    <?php endif ?>
</div>